r_l_project/learning/urls.py
# Workflow 4 -> urls.py/project for workflow 5
from django.conf.urls import url
from learning import views

app_name = 'learning'

urlpatterns = [
    url('register/$', views.register,name='register'),
    url('user_login/',views.user_login,name="user_login"),
]

r_l_project/r_l_project/urls.py
from django.contrib import admin
from django.urls import path
# Workflow 5 -> views.py/app for workflow 6
from django.conf.urls import include
from learning import views
urlpatterns = [
    path('',views.index, name='index'),
    path('learning/',include('learning.urls')),
    path('thank/',views.thank,name='thank'),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name ="user_logout"),
]

r_l_project/learning/models.py
# Workkflow 1 -> forms.py for workflow 2
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional fields
    profile_link = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

# NEVER FORGET TO PERFORM MIGRATIONS

r_l_project/learning/forms.py
# Workflow 2 -> admin.py for workflow 3
from django.contrib.auth.models import User
from django import forms
from learning.models import UserProfileInfo

class UserInfoForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('profile_link','profile_pic')

r_l_project/learning/views.py
# Workflow 6 ->  Templates base.html for Workflow 7 and from there everything is awesome.
from django.shortcuts import render
from learning.forms import UserInfoForm, UserProfileInfoForm

# Helper Libraies
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request,'learning_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def thank(request):
    return render(request,'learning_app/thank.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserInfoForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Form Validation
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save() # save it directly to database, commit= True by default
            user.set_password(user.password) # Encrypted password
            user.save() # update it in database

            profile =  profile_form.save(commit=False)
            profile.user = user # One to One relation with the user_form

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserInfoForm()
        profile_form = UserProfileInfoForm()
    
    return render(request,'learning_app/registration.html',{

        'user_form':user_form,
        'profile_form':profile_form,
        'registered': registered

    })


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:
                # Log the user in.
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password)) # Debug
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'learning_app/login.html', {})

r_l_project/templates/learning_app/base.html
<!--Workflow 7 From here decide your own workflow-->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'learning:register' %}">Register</a>

        {# Some logic on what to display for last item#}
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
        {% else %}
          <a class="nav-link" href="{% url 'learning:user_login' %}">Login</a>
        {% endif %}
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

r_l_project/templates/learning_app/index.html
{% extends 'learning_app/base.html' %}
{% load static %}

{% block body_block %}
    <div class='container'>
        <div class='jumbotron'>
            {% if user.is_authenticated %}
                <h1>Welcome to Index Page! {{ user.username }}</h1>
            {% else %}
                <h2>Welcome to the site!</h2>
            {% endif %}
        </div>
    </div>
{% endblock %}

r_l_project/templates/learning_app/login.html
{% extends 'learning_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'learning:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

r_l_project/templates/learning_app/registration.html
{% extends 'learning_app/base.html' %}
{% load static %}

{% block body_block %}
    <div class="container">
        <div class="jumbotron">
            {% if registered %}
                <h1>Your are registered</h1>
            {% else %}
            <h1>Register Here!</h1>
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{user_form.as_p}}
                {{profile_form.as_p}}
                <input type="submit" value="Submit">
            </form>
            {% endif %}
        </div>
    </div>
{% endblock %}